[monitor:///data/cowrie/log/cowrie.json]
disabled = 0
index = main
sourcetype = cowrie:json
source = cowrie_json

[monitor:///data/cowrie/log/cowrie.log]
disabled = 0
index = main
sourcetype = cowrie:log
source = cowrie_text_log

[monitor:///data/dionaea/log/dionaea]
disabled = 0
index = main
sourcetype = dionaea:log
source = dionaea_log
recursive = true
