[cowrie:json]
SHOULD_LINEMERGE = false
KV_MODE = json
TRUNCATE = 20000
TIME_PREFIX = "timestamp":\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6N%z

[cowrie:log]
SHOULD_LINEMERGE = false
TRUNCATE = 20000

[dionaea:log]
SHOULD_LINEMERGE = false
TRUNCATE = 20000
